// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Swift Student Challenge Real",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Swift Student Challenge Real",
            targets: ["AppModule"],
            bundleIdentifier: "Luis.Swift-Student-Challenge-Real",
            teamIdentifier: "WY36GU57Q5",
            displayVersion: "26.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .heart),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)